name: Build Nugets
run-name: 🐥 ${{ github.actor }} triggered nugget push on ${{ github.ref_name }}
on:
  workflow_dispatch:
  push:
    paths:
    # List of CS PROJECTS TO FILTER
      - 'path to csproj'
    branches:
      - 'main'
      - 'master'
      - 'prod'

jobs:
  build_nugets:
    name: Build ${{matrix.nugets.name}}
    uses: immedis/.github/.github/workflows/build-nuget.yaml@main
    with:
      nuget_feedname: "github"
      id: ${{ matrix.nugets.id }}
      csprj: ${{ matrix.nugets.csprj }}
      dotnet_version: "5.x"
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    strategy:
      matrix:
        nugets:
          - id: # Idenitifer Name for Package
            csprj: # Path to CS PROJECT
          - id: # Idenitifer Name for Package
            csprj: # Path to CS PROJECT

