name: Build Nuget
on:
  workflow_call:
    inputs:
      nuget_feedname:
        required: true
        type: string
      csprj:
        required: true
        type: string
      dotnet_version:
        required: true
        type: string
    secrets:
      packaging_nuget_username:
        required: true
      github_packaging_nuget_pat:
        required: true
jobs:
  build_nugets:
    name: Build ${{inputs.nuget_feedname}}
    env:
      BUILD_CONFIG: 'Release'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{inputs.dotnet_version}}
      - name: Push ${{matrix.nugets.name}}
        run: |
          dotnet nuget update source ${{ inputs.nuget_feedname }} --username "${{secrets.packaging_nuget_username}}" --password "${{secrets.github_packaging_nuget_pat}}" --store-password-in-clear-text
          dotnet restore "${{ inputs.csprj }}"
          dotnet build --no-restore -c ${BUILD_CONFIG} "${{ inputs.csprj }}"
          dotnet pack --no-build -c ${BUILD_CONFIG} --output ./nuget "${{ inputs.csprj }}"
          dotnet nuget push ./nuget/ --api-key "${{secrets.github_packaging_nuget_pat}}" --source "${{ inputs.nuget_feedname }}" --skip-duplicate

