name: Build Nuget
on:
  workflow_call:
    inputs:
      nuget_feedname:
        required: true
        type: string
      id:
        required: true
        type: string
      csprj:
        required: true
        type: string
      dotnet_version:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
jobs:
  build_nugets:
    name: Build ${{inputs.id}}
    env:
      BUILD_CONFIG: 'Release'
    runs-on: ["self-hosted", "linux", "x64", "dev"]
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: eu-west-1
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{inputs.dotnet_version}}
      - name: Get Secrets from AWS
        uses: abhilash1in/aws-secrets-manager-action@v2.1.0
        with:
          secrets: |
            github/packaging/nuget
          parse-json: true
      - name: Push ${{matrix.nugets.name}}
        run: |
          dotnet nuget update source ${{inputs.nuget_feedname}} --username "${GITHUB_PACKAGING_NUGET_USERNAME}" --password "${GITHUB_PACKAGING_NUGET_PAT}" --store-password-in-clear-text
          dotnet restore "${{ inputs.csprj }}"
          dotnet build --no-restore -c ${BUILD_CONFIG} "${{ inputs.csprj }}"
          dotnet pack --no-build -c ${BUILD_CONFIG} --output ./nuget "${{ inputs.csprj }}"
          dotnet nuget push ./nuget/ --api-key "${GITHUB_PACKAGING_NUGET_PAT}" --source "${{ inputs.nuget_feedname }}" --skip-duplicate

